### ISSUE TITLE
Property 'length' of undefined when using web-worker

### ISSUE THREAD

**Issue by Thyoity** [nextapps-de/flexsearch#62] opened 2019-03-07 15:28 UTC
I tried setting the "worker" option to false and everything worked very well. But when I enable this option and set it to any number different than false, my console prints "Uncaught (in promise) TypeError: Cannot read property 'length' of undefined".

Here is the screenshot:

![screenshot_7](https://user-images.githubusercontent.com/10885945/53967496-191baf80-40d4-11e9-9677-e8c6a69c1e99.jpg)

![image](https://user-images.githubusercontent.com/10885945/53967589-47998a80-40d4-11e9-9b12-db1a74279972.png)

I have around 30.000 items, thats why I want to use the web worker feature.

Any ideas? I can give another informations if necessary.

**Comment by ts-thomas** [comment] 2019-03-07 16:32
Hello thanks for the report. The problem is that worker have some missing functionality of handling documents. I'm trying to provide a fix for this as soon as possible.

**Comment by eljefedelrodeodeljefe** [comment] 2019-03-30 15:41
Also looking for this. If you push this further onto the roadmap, let me know, as I can try being of help. Thx.

**Comment by ts-thomas** [comment] 2019-03-31 12:28
__Current state__

I have added most of the missing features that worker needs to handle documents. During this changes I also added a new distribution model between worker instances to support multi-field-search in parallel (that's a big plus). It has turned out that this distribution is not easy to solve. But I'm optimistic that this will be ready very soon.

**Comment by valdrox** [comment] 2019-06-20 20:22
Great package! 

I have a pretty big json document I want to search, and was wondering if Web workers are even working at all, since they would speed things up it seems.

I am trying to get search via web workers working, but I keep getting undefined search results whenever I set the worker to an integer, which seems similar to this issue.

I tried using the example in the documentation, but that doesn't seem to be working (on jsbin or my local project).
 
`var index = new FlexSearch({
    encode: "icase",
    tokenize: "full",
    async: true,
    worker: 4
});

index.add(10025, "John Doe");

index.search("John Doe", function(results){
   console.log(results) // undefined   
});

index.search("John Doe").then(function(results){
    console.log(results)// undefined     
});`
I would expect it to return an array with 10025.

Is there an extra step somewhere that i'm missing?

**Comment by nickdandakis** [comment] 2019-07-25 20:34
I'm seeing roughly the same thing as @valdrox, except instead of getting `undefined` back, I get an empty array (`[]`).

**Comment by ts-thomas** [comment] 2019-07-26 17:26
Please notice, that Workers does not work within Node.js, it is just available through a Browser. Running multiple instances in Node.js is basically implemented in FlexSearch-Server. I need to move this capability to the client to make a Worker-fallback available in Node.js

**Comment by ts-thomas** [comment] 2019-07-26 18:13
I found out that using workers when indexing documents (instead of id-content-pairs) did not work actually. Workers needs a re-implementation to split threads through document fields.

**Comment by nickdandakis** [comment] 2019-07-26 18:14
@ts-thomas I was on an earlier version (v0.6.22) instead of latest, where workers weren't working for me even with id-content-pairs. However, using the latest and the callback version of `search()`, I can get it to work now.

**Comment by ts-thomas** [comment] 2021-06-28 13:48
Please change over to the version >= 0.7.x, thanks a lot.

**Closed by ts-thomas** 2021-06-28 13:48 UTC
Labels: bug, enhancement
